repos:
  - repo: local
    hooks:
      - id: prolog-tests
        name: Run Prolog tests
        entry: test-bits
        language: system
        files: \.pl$
        pass_filenames: false
      - id: prolog-tags
        name: Generate Prolog tags file
        entry: generate-ctags
        language: system
        files: \.pl$
        pass_filenames: false
